name: ai_dnm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 
  bloc: 
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
